### ISSUE TITLE
Block corysimmons

### ISSUE THREAD

**Issue by shinnn** [imagemin/meta#13]
@kevva @sindresorhus 

Sorry I know this is boring request but please add `corysimmons` to [per-organization blocking users](https://help.github.com/articles/blocking-a-user-from-your-organization/).

In other projects I saw he've discouraged a lot of OSS maintainers, including me, with his impoliteness and offensiveness.

* https://github.com/stylelint/stylelint-config-standard/issues/6
* https://github.com/stylelint/stylelint/issues/719
* https://github.com/stylelint/stylelint/pull/720
* https://github.com/sindresorhus/pageres/pull/288
* (and others already deleted)

I'm 100% sure he'll do mental harm to the imagemin maintainers and users in the future.

I don't have permission to update imagemin organization settings, so I'd like Sindre or Kevin to do it.

**Comment by corysimmons** [comment]
Agreed I was out of line in the stylelint project -- which I apologized to the maintainers for after reflecting on it (in fact, one of them I've had pretty friendly conversations with since then) and they seemed to be humans about it and understand that people get frustrated and say/do stupid things some times. What's important is having the integrity to admit when you were wrong and learn from mistakes.

I don't think what I've said on PageRes is "discouraging" at all. I think you're just trying to manipulate @sindresorhus -- I wasn't particularly rude, and even already said I was bowing out of that PR to avoid detracting from the PR itself.

I just don't like when people do good work and it gets thrown away for pedantry -- especially when there was an issue where the maintainer [actually requested](https://github.com/sindresorhus/pageres/issues/238#issuecomment-183599937) a very similar -- yet not-as-nice -- feature. People's time is valuable. If you don't want the feature, be more explicit before someone wastes hours of their life working on _your_ project.

And it's interesting I offer to do research for imagemin and you claim I will "100% do mental harm" and want to ban me from the organization entirely before I've even done anything.

Good job trying to publicly shame me, but I really don't care about my reputation as much as you, and your Twitter-tier Gitter buddies would hope.

I'll continue to work on imagemin if I want -- whether it be this username/IP or another.

Sorry if I mentally harmed you by refuting this.

**Comment by corysimmons** [comment]
Is there an uneddit for GitHub since @shinnn deleted my extensive rebuttal to this issue?

**Comment by corysimmons** [comment]
Why do you keep deleting my rebuttals to this? Is it because you want to manipulate @sindresorhus without any obstacles?

**Comment by AndrewJHart** [comment]
I'm sorry but this is ridiculous. I know there are abusive maintainers and contributors out there but this is no way to solve the problem.. Being progressive with banning someone? That's downright nonsensical. If he has caused problems for this project then so be it - ban him. I know the guy - sometimes he's a dick (but we all have our days... its true) but he has a lot to contribute and he's actually quite brilliant. Just my 2 cents...

**Comment by sindresorhus** [comment]
@corysimmons We try to create friendly and welcoming projects. Taking your frustration out on maintainers that provide code for free in their free time doesn't help their motivation. Many people get burned out in open source by this. In Pageres, I was just telling you that saying something is "stupid/nasty" isn't a good technical argument. That being said, I'm gonna give another chance on my repos. Please try to be nice and keep in mind that sarcasm doesn't work well on text :)

@shinnn Next time, just contact me privately about cases like this. You now have Owner rights to this organization. Up to you whether to block him here.

**Comment by shinnn** [comment]
> just contact me privately about cases like this.

Sorry I should have done that and tried to keep this issue tracker clean.

> You now have Owner rights to this organization. Up to you whether to block him here.

Thanks. *For now*, I don't change the block setting of this organization. I hope the time will never comes for me to revisit it.
